.TH "HAUI" "" "March 2014" "" ""
.SH "NAME"
\fBhaui\fR
.P
Haui, the "Home Automation UI"
.P
Mainly just a placeholder for future goodness\.\.\.but, it currently supports sending most X10 events via a CM11 interface and is configured via a simple JSON settings file\.
.P
WARNING: The X10 module being used has stability issues, at least with my own personal X10 interface\.\.\.
.SH Install and Setup
.P
.RS 2
.EX
$ npm install haui \-g
$ haui \./path/to/settings\-file\.json
.EE
.RE
.SH Example Settings JSON
.P
The \fBuri\fR property is optional, simply provided as a way to override what gets used in the HTML (Jade) view\.
.P
.RS 2
.EX
{
  "x10": { "serialPath": "/dev/ttyUSB0" },
  "port": 8000,
  "host": "127\.0\.0\.1",
  "uri": "http://127\.0\.0\.1:8000",
  "buttons": [
    {
      "label": "Livingroom \- Front \- ON",
      "command": "ON",
      "house": "A",
      "unit": "1"
    },
    {
      "label": "Livingroom \- Front \- OFF",
      "command": "OFF",
      "house": "A",
      "unit": "1"
    },
    {
      "label": "Livingroom \- Hall \- ON",
      "command": "ON",
      "house": "A",
      "unit": "2"
    },
    {
      "label": "Livingroom \- Hall \- OFF",
      "command": "OFF",
      "house": "A",
      "unit": "2"
    }
  ]
}
.EE
.RE
.SH Screenshot
.P
Screenshot \fIhttps://github\.com/randallagordon/haui/raw/master/img/readme\-screenshot\.png\fR
.SH CHANGELOG
.SS v0\.0\.2
.RS 0
.IP \(bu 2
Fix path resolution, add optional logging with \'good\'

.RE
.SS v0\.0\.1
.RS 0
.IP \(bu 2
First release, sorely lacking in awesome\.\.\.

.RE
.SH TODO
.RS 0
.IP \(bu 2
Leverage node\-lirc \fIhttps://github\.com/alexbain/lirc_node\fR for home theater control
.IP \(bu 2
Create a non\-crap UI

.RE
.SH LICENSE
.P
MIT

